<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Update="appsettings.*.json">
            <DependentUpon>appsettings.json</DependentUpon>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content >
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.17.1" />
        <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.8.0" />
        <PackageReference Include="Microsoft.Extensions.Azure" Version="1.13.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Modules\Telegram\FeedMind.Modules.Telegram\FeedMind.Modules.Telegram.csproj" />
    </ItemGroup>

</Project>
