<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />

    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Telegram\FeedMind.Modules.Telegram.Contracts\FeedMind.Modules.Telegram.Contracts.csproj" />
      <ProjectReference Include="..\FeedMind.Modules.Filtering.Contracts\FeedMind.Modules.Filtering.Contracts.csproj" />
    </ItemGroup>

</Project>
