<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="appsettings.*.json" Exclude="appsettings.json">
            <DependentUpon>appsettings.json</DependentUpon>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.17.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Modules\Telegram\FeedMind.Modules.Telegram\FeedMind.Modules.Telegram.csproj" />
    </ItemGroup>

</Project>
