name: Build and Deploy Job

on:
  workflow_dispatch:

jobs:
  development:
    name: Development
    runs-on: ubuntu-latest

    steps:
      - name: Show info
        run: |
          echo "Test build and deploy job workflow"