name: Build and Deploy Job

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Show debug logs
        required: true
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: pvmacr
  ACR_REPOSITORY_NAME: "pvmacr-dqc7dxbwf7fzewf2.azurecr.io/feedmind-channel-sync-job"
  CONTAINER_APP_JOB_NAME: feedmind
  RESOURCE_GROUP: rg-pvm-feedmind-dev

jobs:
  development:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Build Number
        id: build_number
        uses: ./.github/actions/build-number

      - name: Create Image Tag
        id: create_image_tag
        uses: ./.github/actions/create-image-tag
        with:
          build-number: ${{ steps.build_number.outputs.build_number }}

      - name: Azure Login (OIDC)
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker image and push to ACR
        run: |
          docker build -f Dockerfile.job -t ${{ env.ACR_REPOSITORY_NAME }}:${{ steps.create_image_tag.outputs.image_tag }} .
          docker push ${{ env.ACR_REPOSITORY_NAME }}:${{ steps.create_image_tag.outputs.image_tag }}

      - name: Copy app settings
        env:
          AZURE_STORAGE_ACCOUNT: stpvmdev
          AZURE_SHARE_NAME: mnt
          AZCOPY_AUTO_LOGIN_TYPE: AZCLI
          SETTINGS_SOURCE_FILE_PATH: "./src/Hosts/FeedMind.ChannelSyncJob/appsettings.dev.json"
          SETTINGS_DESTINATION_FILE_PATH: "feedmind-channel-sync-job/appsettings.json"
        run: |
          azcopy copy "$SETTINGS_SOURCE_FILE_PATH" \
            "https://$AZURE_STORAGE_ACCOUNT.file.core.windows.net/$AZURE_SHARE_NAME/$SETTINGS_DESTINATION_FILE_PATH" \
            --recursive=false

      - name: Deploy to Azure Container App Job
        run: |
          az containerapp job update \
            --name caj-${{ env.CONTAINER_APP_JOB_NAME }}-dev \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_REPOSITORY_NAME }}:${{ steps.create_image_tag.outputs.image_tag }} \
            ${{ inputs.debug && '--debug' || '' }}