name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Show debug logs
        required: true
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Azure Login (OIDC)
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az deployment group create \
            --resource-group rg-pvm-feedmind-dev \
            --template-file ./pipelines/bicep/infrastructure/main.bicep \
            --parameters ./pipelines/bicep/infrastructure/parameters.bicepparam \
            --what-if \

          az deployment group create \
            --resource-group rg-pvm-feedmind-dev \
            --template-file ./pipelines/bicep/infrastructure/main.bicep \
            --parameters ./pipelines/bicep/infrastructure/parameters.bicepparam \
            ${{ inputs.debug && '--debug' || '' }}
